Login signup
varun-Tad/Dress-up pull request #2
Opened 2022-02-11 12:06 UTC by varun-Tad

Created login and sign up.Please review

2022-02-11 12:13 UTC, sri-rishi requested changes
Give signup and login page padding or margin from bottom

2022-02-11 12:16 UTC, sri-rishi requested changes

2022-02-11 12:16 UTC, sri-rishi commented on Pages/Login-page/login.css
> +
remove extra spacing

2022-02-11 12:16 UTC, sri-rishi commented on Pages/Login-page/login.css
> +    display: flex;
you have used two time display: flex

2022-02-11 12:16 UTC, sri-rishi commented on Pages/Login-page/login.css
> +    margin-right:3rem;
You can give padding and margin as shorthand property

2022-02-11 12:16 UTC, sri-rishi commented on Pages/Login-page/login.css
> +    grid-template-columns: repeat(2,1fr); */
remove comments

2022-02-11 12:27 UTC, varun-Tad commented
Thanks for the review @sri-rishi . Will make the changes

2022-02-11 18:55 UTC, gauravsinhaweb requested changes

2022-02-11 18:55 UTC, gauravsinhaweb commented on Pages/Login-page/login.css
> +    padding:0 0.5rem 0 2rem;
use px for value less than 10px

2022-02-11 18:55 UTC, gauravsinhaweb commented on Pages/Login-page/login.css
> +
remove extra spacing

2022-02-11 18:55 UTC, gauravsinhaweb commented on Pages/Login-page/login.css
> +    color:#333;
use variable colors

2022-02-11 18:55 UTC, gauravsinhaweb commented on Pages/Login-page/login.css
> +     bottom: 130px;
use rems for responsiveness.

2022-02-11 18:55 UTC, gauravsinhaweb commented on Pages/Login-page/login.html
> +
remove unnecessary comments. Nice work!

2022-02-12 04:49 UTC, varun-Tad commented
Will make the required changes.Thanks for the review @gauravsinhaweb

2022-02-12 05:17 UTC, merged