Product Page
varun-Tad/Dress-up pull request #3
Opened 2022-02-12 13:42 UTC by varun-Tad

Created product page.Please Review

2022-02-12 14:30 UTC, sri-rishi requested changes
![Screenshot (25)](https://user-images.githubusercontent.com/72429483/153715324-b138cb56-1b3e-4a44-86f1-21f6fe5d612b.png)
 
It's overflowing

2022-02-12 14:30 UTC, sri-rishi commented on Pages/prod-listing/prod-list.css
> +
remove extra spacing

2022-02-12 14:43 UTC, varun-Tad commented
but it's not overflowing for me. wonder why it's overflowing for you @sri-rishi

2022-02-12 15:03 UTC, varun-Tad commented
Can you check in another browser maybe, if it's overflowing for you because it's not overflowing for me anywhere @sri-rishi

2022-02-12 17:01 UTC, sri-rishi commented
> but it's not overflowing for me. wonder why it's overflowing for you @sri-rishi

Then it's good to merge

2022-02-13 04:03 UTC, yaswanthmyneni commented on Pages/prod-listing/prod-list.css
> +  }
Use object-fit property here to get clear images for carts.
![Screenshot 2022-02-13 at 9 21 03 AM](https://user-images.githubusercontent.com/79623546/153738092-ff188ea3-d57b-4c36-9a50-fbbc61d8e327.png)

2022-02-13 04:06 UTC, yaswanthmyneni commented on Pages/prod-listing/prod-list.css
> +    z-index: 11;
Just a suggestion, if you want can do according to the images.
![Screenshot 2022-02-13 at 9 25 52 AM](https://user-images.githubusercontent.com/79623546/153738148-9f65c9b7-edf1-4a25-b6d6-2ce8bc1d384f.png)
![Screenshot 2022-02-13 at 9 28 21 AM](https://user-images.githubusercontent.com/79623546/153738154-8400b5eb-b819-4e22-a061-bbbca0ae1320.png)
![Screenshot 2022-02-13 at 9 29 30 AM](https://user-images.githubusercontent.com/79623546/153738163-ed3bef23-426c-4377-867a-0d2d1c530912.png)

2022-02-13 05:25 UTC, merged